//  This file is automatically generated. DO NOT EDIT, all your changes would be lost.
//  https://pub.dartlang.org/packages/iconfont_convert

import 'package:material_ui/material_ui.dart';

class LiveIcons {
  static const String _family = 'iconfont';

  LiveIcons._();

  static const IconData douyu = IconData(0xe613, fontFamily: _family); // douyu
  static const IconData huya = IconData(0xe614, fontFamily: _family); // 虎牙
}

class _PreviewIcon {
  const _PreviewIcon(this.icon, this.name, this.propName);

  final IconData icon;
  final String name;
  final String propName;
}

class LiveIconsPreview extends StatelessWidget {
  const LiveIconsPreview({super.key});

  static const iconList = <_PreviewIcon>[
    _PreviewIcon(LiveIcons.douyu, "douyu", "douyu"),
    _PreviewIcon(LiveIcons.huya, "huya", "虎牙"),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('LiveIcons'),
      ),
      body: GridView.count(
        shrinkWrap: true,
        crossAxisCount: 4,
        children: iconList.map((e) {
          return InkWell(
            onTap: () {
              //
            },
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Container(
                  margin: const EdgeInsets.only(bottom: 8),
                  child: Icon(e.icon),
                ),
                Text(e.name, style: const TextStyle(fontSize: 12), overflow: TextOverflow.ellipsis, maxLines: 1),
                Text(e.propName, style: const TextStyle(fontSize: 12), overflow: TextOverflow.ellipsis, maxLines: 1),
              ],
            ),
          );
        }).toList(),
      ),
    );
  }
}
